version: '3'

networks:
  idig-net:
    driver: bridge

name: idig-server

services:
  idig-server:
    image: unillett/idig:latest-server
    build:
      context: ./
      dockerfile: server.dockerfile
    volumes:
      - ./server-data:/server/data
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - idig-net
    container_name: idig-server
    restart: always
