version: '3'

networks:
  idig-net:
    driver: bridge

name: idig-server

services:
  idig-server:
    image: idig-server:latest
    build:
      context: ./
      dockerfile: dockerfile-server
    volumes:
      - ./server-data:/server/data
    ports:
      - "9000:9000"
    networks:
      - idig-net
    container_name: idig-server
    restart: always
